# AppVeyor build definition
# http://www.appveyor.com/docs/appveyor-yml

version: 0.2.{build}

pull_requests:
  do_not_increment_build_number: true

branches:
  only:
  - master

environment:
  PowerShellGalleryApiKey:
    secure: ej6Bf8C17OGD+9ozkDrfwsYbpPJavwHAbZ5MHI0g/F4KgFDcygliwuBSRlmQImku

install:
- ps: .\init.ps1

build_script:
- ps: |
      Invoke-psake Build -NoLogo -NoTR
      if (-not $psake.build_success) { exit 1 }

test_script:
- ps: |
      Invoke-psake Test -NoLogo -NoTR
      if (-not $psake.build_success) { exit 1 }

deploy_script:
- ps: |
      Invoke-psake Publish -NoLogo -NoTR -parameters @{ "moduleVersion" = $env:APPVEYOR_BUILD_VERSION }
      if (-not $psake.build_success) { exit 1 }
